name: This-is-my-life
favicon: null
layout_spectrum: 0.6783029
typography_spectrum: 0.1573576
title: This is My Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F3F5F4'
    - '#3495E3'
    - '#505251'
    - '#8EC375'
    - '#82EDFF'
  brandStrength: 0
  lightness: 0.4763695
  saturation: 1
  rhythmicContrast: 0.480666
purpose: []
